for stringId, value in pairs(UNBOXER_STRINGS) do
    ZO_CreateStringId(stringId, value)
end
UNBOXER_STRINGS = nil

ZO_CreateStringId("SI_UNBOXER_BATTLEGROUND_LOWER", LocaleAwareToLower(GetString("SI_INSTANCEDISPLAYTYPE", INSTANCE_DISPLAY_TYPE_BATTLEGROUND)))
ZO_CreateStringId("SI_UNBOXER_TRIAL_LOWER", LocaleAwareToLower(GetString("SI_LFGACTIVITY", LFG_ACTIVITY_TRIAL)))
ZO_CreateStringId("SI_UNBOXER_UNDAUNTED_LOWER", LocaleAwareToLower(GetString("SI_VISUALARMORTYPE", VISUAL_ARMORTYPE_UNDAUNTED)))
ZO_CreateStringId("SI_UNBOXER_WEEKLY_LOWER", LocaleAwareToLower(GetString(SI_RAID_LEADERBOARDS_WEEKLY)))
ZO_CreateStringId("SI_UNBOXER_CRAFTED_LOWER", LocaleAwareToLower(GetString(SI_ITEM_FORMAT_STR_CRAFTED)))
ZO_CreateStringId("SI_UNBOXER_REWARD_LOWER", LocaleAwareToLower(GetString(SI_LEVEL_UP_REWARDS_GAMEPAD_REWARD_SECTION_HEADER_SINGULAR)))